### ISSUE TITLE
Update Page for Mini Summit Agenda and Details

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#1]
We can update the Mini Summit Page - https://www.opensds.io/oda-mini-summit-kubecon-eu-2019

To have:
Agenda,
Speakers
More information on the event etc...
Register link etc.

**Comment by anvithks** [comment]
This page is under construction.

**Comment by anvithks** [comment]
This page has now been updated.

https://www.opensds.io/mini-summit-kubecon-eu-2019
