### ISSUE TITLE
Urgent Update - https://www.opensds.io/mini-summit-kubecon-eu-2019

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#13]
1.  Wherever Hall 8, Room F3 --> please add Fira Barcelona Gran Via also [Actual Venue information]
2. Speakers Photo Update
3. Speakers Name update in the photo area
4. Remove "Note: The current event schedule is not final and may get updated." from schedule
5.  Please update the topic title for Kei Kusunoki as Meeting Multi-Cloud Challenges And Japan EUAC Introduction

**Comment by anvithks** [comment]
- [x]  Wherever Hall 8, Room F3 --> please add Fira Barcelona Gran Via also [Actual Venue information]
- [x] Speakers Photo Update
- [x] Speakers Name update in the photo area
- [x] Remove "Note: The current event schedule is not final and may get updated." from schedule
- [x] Please update the topic title for Kei Kusunoki as Meeting Multi-Cloud Challenges And Japan EUAC Introduction
