### ISSUE TITLE
Provide a form to join as a supporter

### ISSUE THREAD

**Issue by anvithks** [opensds/website#22]
Anyone or any organisation that wishes to join the foundation in a supporter role can use the form. This form also allows the user to submit consent to logo usage and the logo to be used.

**Comment by anvithks** [comment]
@stevenphtan @skdwriting How will this form be different from the Join us form?
What are the different fields and what is the language (legal content, if any) to be displayed to the suer?

**Comment by stevenphtan** [comment]
Where is this page linked from?

**Comment by anvithks** [comment]
@stevenphtan This is currently linked from the Support SODA button under the supporters carousel on the home page. Link is [here](https://sodafoundation.io/the-foundation/join/end-users-supporters/)

**Comment by anvithks** [comment]
The Join page is now updated with options to select the capacity in which a person/institution wants to join the foundation (End User / Developer / Vendor).
