### ISSUE TITLE
People bios

### ISSUE THREAD

**Issue by stevenphtan** [opensds/website#23]
We need to have bios for the Board, TSC, EUAC, OC, AWG, etc. so for the community to know one another better. Also add Twitter, Github, LinkedIn, and maybe popular chatapps like Wechat, Whatsapp.

**Comment by anvithks** [comment]
I have made these changes. All the people have a bios link and social media connects.

**Comment by anvithks** [comment]
This has been completed:
[Governing Board](https://sodafoundation.io/the-foundation/governing-board/)  
[TSC](https://sodafoundation.io/the-foundation/technical-steering-committee/)  
[EUAC](https://sodafoundation.io/the-foundation/end-user-advisory-committee/)  
[OC](https://sodafoundation.io/the-foundation/outreach-committee/)
