### ISSUE TITLE
HOME : Opening Page picture not very impressive - the logo not really visible

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#31]
Home Page First splash pic is not really impressive:
1. The white logo is not visible.
2. The background picture does not really convey anything for "ONE Framework for Data Management" 
3. Is it really "Framework" ? Or Ecosystem? 
4. "One Framework for Data" ? or need to rethink about 'Framework' ?
5.  "One Path to Data Autonomy" ? "One Ecosystem for Data" ? 

-- I think, we should put another picture as landing one. Should we really mention about the launching information now?! Does it have any value? We can simple put a nice background, our logo, name, caption and 2-3 lines of description to read what is soda foundation all about..... this is more valuable for who opens the page.
Can we show as :
Line 1 - Logo - SODA Foundation
Line 2 - "SODA Open Data Autonomy"
Line 3 - <Caption - like One Path to Data Autonomy>

**Comment by skdwriting** [comment]
I think One Data Framework (which is updated is good) :)

**Comment by skdwriting** [comment]
As the image is changed, @anvithks , please update the new image and we can close this issue

**Comment by anvithks** [comment]
@skdwriting The home page has been updated with latest inputs from Ariel.
