### ISSUE TITLE
HOME : SODA Framework Definition 

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#32]
SODA Framework: 
One Framework for Data Management
SODA is an open source unified autonomous data management framework for data mobility from edge to core to cloud.

Can we update this?
One Data Framework, Infinite Possibilities
SODA Framework is an open vendor and application platform agnostic ecosystem framework to  provide seamless data and storage services across Edge, Core and Cloud.

**Comment by anvithks** [comment]
@skdwriting This is changed to 

> an open source data framework enabling data mobility, data protection, data security, data lifecycle, and more

Closing for now. please reopen if needed.
