### ISSUE TITLE
Update https://www.opensds.io/oda-mini-summit-kubecon-eu-2019 page

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#4]
1) ODA Mini Summit  ==> Open Data Autonomy Mini Summit 
2) Please give more details on the Mini Summit in the description itself?
The Open Data Autonomy Mini Summit is an all-day event focusing on data & storage challenges and solutions in cloud native era. The OpenSDS community is working to build an open autonomous data platform integrating all disparate data services, such as data migration, replication, life cycle, protection etc along with AI/ML. The platform is self-governed and intelligent. OpenSDS is a Linux Foundation project and its members include Dell EMC, Fujitsu, Huawei, IBM, Intel, KPN, Linbit, NTT Communications, Toyota, Vodafone, Western Digital, and Yahoo Japan. It is a great opportunity to learn and collaborate to build solutions for cloud native challenges of data autonomy.

The event is organized with Hands-on Workshop (BYOD), Demos, Deep Dive Sessions and End User Sessions. It can provide an end to end experience and networking opportunity during welcome breakfast and evening reception dinner.

3) Can we reduce the header space, so we get more view area and can get the details faster?

**Comment by anvithks** [comment]
I have consolidated the description in one box.  
Reduced the header space to smallest. 
Please note that this is a placeholder page and will be updated with a page that has a sub-menu that allows navigation to sections.
