### ISSUE TITLE
Update https://www.opensds.io/about

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#5]
Please add the project goals view in this page.

Project Introduction:
OpenSDS project was started towards the end of 2016 by a group of companies joined together to resolve key data management pain-points from storage vendors and end users. It was incubated as an open source project under The Linux Foundation to build a community to address those issues in a generic and standardized way.

Project Charter:
Currently, there are multiple challenges and pain points due to siloed data/storage services. This project's vision is to connect all the siloed data solutions to build a self-governed and intelligent data platform which is open, autonomous, ready and real.

Project Goals:
Please add from the home page. (open, autonmous, ready and real)

Project Governance:
The project is currently driven by TSC(Technical Steering Committee), EUAC(End User Advisory Committee) and open source community. It comprises of various organizations and experts from the industry. 
 We can show the link to People 
Show all the member companies here. (or give a link to member companies)

Architecture:
Arch Picture

Interested to join?
<please give all the links needed>

**Comment by anvithks** [comment]
- [x] Updated the content as per above.  

- [x]  Added the project goals section.

- [x] Added links to the TSC and EUAC sections on the People page.

- [x] Added a list of members. Currently added only names in text. We can add logos if we have clearance.  

- [x] Added a Join Now button.
