### ISSUE TITLE
https://www.opensds.io/ home page updates

### ISSUE THREAD

**Issue by skdwriting** [opensds/website#6]
1. Please remove "Current Trends" as of now. (we will see how to bring such info later)
2. After "what is opensds", we can bring the project goals. then the arch. The arch diagram can be bit more smaller and centre aligned.
3. We can have a news / info scroller on the home page - showing about releases , recent events etc... Let us include Kubernetes Day, India meetup group, Japan meetup, china hackathon, open data autonomy mini summit.....etc...

4. Upcoming events --> It is better we provide the event information in the list. Currently only date is there...it is not giving any info unless the user clicks the date.

**Comment by skdwriting** [comment]
Upcoming events -- please update like this (discussed with steven as well)
a)  we can fix say next 4-5 events title, one-liner, date, venue and link associated -- show all. No need to ask the user to click each to get more info.
b) If we have more in the pipeline, "More.." -- will take to the upcoming events page. (where all planned upcoming events information we will show)

**Comment by anvithks** [comment]
- [x] Removed _Current Trends_ section.  

- [x] Rearranged the OpenSDS goals section. The architecture diagram is center aligned currently and the size is kept with legibility of the image contents and clarity. I can try some sizes and see which suits the best. Please note: On monitors / screens with lower resolution (say 1280x800 or 1024x768) all the content will appear larger than it is.  When the minimum width or maximum width or the responsive media queries is reached the content will adapt to the screen size.

**Comment by anvithks** [comment]
TODO: I will need to discuss these with you @skdwriting  before making the changes. The rest I have already done.

- [x] News / Info scroller. This will not be a text scroller like older websites. We can add News / updates to the news category and then display the same as a carousel or grid on the home page. 

- [ ]  We can use the Events plugin that is already installed. I will check if it can serve our purpose. I will then add the  Upcoming events to this and display the same on the home page.

**Comment by anvithks** [comment]
> Upcoming events -- please update like this (discussed with steven as well)
> a) we can fix say next 4-5 events title, one-liner, date, venue and link associated -- show all. No need to ask the user to click each to get more info.
> b) If we have more in the pipeline, "More.." -- will take to the upcoming events page. (where all planned upcoming events information we will show)

Adding a one liner info was not looking good in the format I have displayed the events currently. I will update the same if I can think of anything better.

**Comment by anvithks** [comment]
Added an updated news scroller on the home page.

**Comment by anvithks** [comment]
> TODO: I will need to discuss these with you @skdwriting before making the changes. The rest I have already done.
> 
> * [x]  News / Info scroller. This will not be a text scroller like older websites. We can add News / updates to the news category and then display the same as a carousel or grid on the home page.
> * [ ]   We can use the Events plugin that is already installed. I will check if it can serve our purpose. I will then add the  Upcoming events to this and display the same on the home page.

Added an updated news scroller on the home page.

**Comment by anvithks** [comment]
Site is no longer maintained. Closing this as we are moving to the Soda Foundation website.
https://sodafoundation.io
